/*
 * IRIS-Gateway API
 * ### Encryption of the data to be transmitted (contact data) In order to be not limited in the amount of data, a hybrid encryption with symmetric encryption of the data and asymmetric encryption of the symmetric key is used for the encryption of the contact data.    1. The apps and applications get the public key of the health department as a 4096-bit RSA key from the IRIS+ server. This key is base64-encoded similar to the Private Enhanced Mail (PEM) format but without key markers (-----BEGIN PUBLIC KEY----- / -----END PUBLIC KEY-----).   2. The app generates a 256-bit AES key.   3. The data is encrypted with this key (algorithm: AES/CBC/PKCS5Padding and 16 byte IV)   4. IV bytes are prepended to the cipher text. Those merged bytes represent the encrypted content.   5. The AES key must be encrypted with the public RSA key of the health department. (algorithm: RSA with Optimal Asymmetric Encryption Padding (OAEP) \"RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING\")   6. The encrypted AES key and the encrypted content must be transmitted base64 encoded.    #### Schematic sequence    ```   pubKeyEncryption = publicKeyFromBase64(givenPublicKey);   contentKey = generateAESKey();   iv = generateRandomBytes(16);    encrypted = contentKey.encrypt(content, \"AES/CBC/PKCS5Padding\", iv);   keyEncrypted = pubKeyEncryption.encrypt(contentKey, \"RSA/NONE/OAEPWithSHA3-256AndMGF1Padding\");    submissionDto.encryptedData = base64Encode(concat(iv,encrypted));   submissionDto.secret = base64Encode(keyEncrypted);   ``` 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: jens.kutzsche@gebea.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package iris.demo.contact_diary_app.model;

import java.util.Objects;

/**
 * Address
 */
public class Address {
	public static final String SERIALIZED_NAME_STREET = "street";
	private String street;

	public static final String SERIALIZED_NAME_HOUSE_NUMBER = "houseNumber";
	private String houseNumber;

	public static final String SERIALIZED_NAME_ZIP_CODE = "zipCode";
	private String zipCode;

	public static final String SERIALIZED_NAME_CITY = "city";
	private String city;

	public Address street(String street) {

		this.street = street;
		return this;
	}

	/**
	 * Get street
	 * 
	 * @return street
	 **/

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public Address houseNumber(String houseNumber) {

		this.houseNumber = houseNumber;
		return this;
	}

	/**
	 * Get houseNumber
	 * 
	 * @return houseNumber
	 **/

	public String getHouseNumber() {
		return houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	public Address zipCode(String zipCode) {

		this.zipCode = zipCode;
		return this;
	}

	/**
	 * Get zipCode
	 * 
	 * @return zipCode
	 **/

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public Address city(String city) {

		this.city = city;
		return this;
	}

	/**
	 * Get city
	 * 
	 * @return city
	 **/

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Address address = (Address) o;
		return Objects.equals(this.street, address.street) &&
				Objects.equals(this.houseNumber, address.houseNumber) &&
				Objects.equals(this.zipCode, address.zipCode) &&
				Objects.equals(this.city, address.city);
	}

	@Override
	public int hashCode() {
		return Objects.hash(street, houseNumber, zipCode, city);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Address {\n");
		sb.append("    street: ").append(toIndentedString(street)).append("\n");
		sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
		sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
		sb.append("    city: ").append(toIndentedString(city)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
