/*
 * IRIS-Gateway API
 * ### Encryption of the data to be transmitted (contact data) In order to be not limited in the amount of data, a hybrid encryption with symmetric encryption of the data and asymmetric encryption of the symmetric key is used for the encryption of the contact data.    1. The apps and applications get the public key of the health department as a 4096-bit RSA key from the IRIS+ server. This key is base64-encoded similar to the Private Enhanced Mail (PEM) format but without key markers (-----BEGIN PUBLIC KEY----- / -----END PUBLIC KEY-----).   2. The app generates a 256-bit AES key.   3. The data is encrypted with this key (algorithm: AES/CBC/PKCS5Padding and 16 byte IV)   4. IV bytes are prepended to the cipher text. Those merged bytes represent the encrypted content.   5. The AES key must be encrypted with the public RSA key of the health department. (algorithm: RSA with Optimal Asymmetric Encryption Padding (OAEP) \"RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING\")   6. The encrypted AES key and the encrypted content must be transmitted base64 encoded.    #### Schematic sequence    ```   pubKeyEncryption = publicKeyFromBase64(givenPublicKey);   contentKey = generateAESKey();   iv = generateRandomBytes(16);    encrypted = contentKey.encrypt(content, \"AES/CBC/PKCS5Padding\", iv);   keyEncrypted = pubKeyEncryption.encrypt(contentKey, \"RSA/NONE/OAEPWithSHA3-256AndMGF1Padding\");    submissionDto.encryptedData = base64Encode(concat(iv,encrypted));   submissionDto.secret = base64Encode(keyEncrypted);   ``` 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: jens.kutzsche@gebea.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package iris.demo.contact_diary_app.model;

import java.util.Objects;

/**
 * This data must be encrypted with the key of health department from DataRequest.keyOfHealthDepartment and must be
 * encoded with Base64!(&#x60;dataToTransport&#x60; in the general description of the API.)
 */
public class ContactsAndEvents {
	public static final String SERIALIZED_NAME_CONTACTS = "contacts";
	private ContactPersonList contacts;

	public static final String SERIALIZED_NAME_EVENTS = "events";
	private EventList events;

	public static final String SERIALIZED_NAME_DATA_PROVIDER = "dataProvider";
	private ContactsAndEventsDataProvider dataProvider;

	public ContactsAndEvents contacts(ContactPersonList contacts) {

		this.contacts = contacts;
		return this;
	}

	/**
	 * Get contacts
	 * 
	 * @return contacts
	 **/

	public ContactPersonList getContacts() {
		return contacts;
	}

	public void setContacts(ContactPersonList contacts) {
		this.contacts = contacts;
	}

	public ContactsAndEvents events(EventList events) {

		this.events = events;
		return this;
	}

	/**
	 * Get events
	 * 
	 * @return events
	 **/

	public EventList getEvents() {
		return events;
	}

	public void setEvents(EventList events) {
		this.events = events;
	}

	public ContactsAndEvents dataProvider(ContactsAndEventsDataProvider dataProvider) {

		this.dataProvider = dataProvider;
		return this;
	}

	/**
	 * Get dataProvider
	 * 
	 * @return dataProvider
	 **/

	public ContactsAndEventsDataProvider getDataProvider() {
		return dataProvider;
	}

	public void setDataProvider(ContactsAndEventsDataProvider dataProvider) {
		this.dataProvider = dataProvider;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ContactsAndEvents contactsAndEvents = (ContactsAndEvents) o;
		return Objects.equals(this.contacts, contactsAndEvents.contacts) &&
				Objects.equals(this.events, contactsAndEvents.events) &&
				Objects.equals(this.dataProvider, contactsAndEvents.dataProvider);
	}

	@Override
	public int hashCode() {
		return Objects.hash(contacts, events, dataProvider);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ContactsAndEvents {\n");
		sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
		sb.append("    events: ").append(toIndentedString(events)).append("\n");
		sb.append("    dataProvider: ").append(toIndentedString(dataProvider)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
