ALTER TABLE ALERTS RENAME COLUMN ALERT_TYPE TO MESSAGE_TYPE;
ALTER TABLE ALERTS RENAME constraint alert_pkey TO message_pkey;
ALTER TABLE ALERTS ADD sender varchar(256) NULL;
ALTER TABLE ALERTS RENAME TO MESSAGES;
