:toc: macro

# Gateway

IRIS stands for "Integration of Remote systems into Infection control Software" and is intended to be the central point of mediation between the various contact, event and guest tracking apps on the one hand and the infection control software (e.g. SORMAS) in the health departments on the other.

This repository is used to manage the development and source code of IRIS connect.

NOTE: The IRIS connect is work in progress. If you are interested or have questions please reach out to us.

toc::[]

=== Libraries

The services are based on the following open source projects:

- Spring Boot 2.4
- Spring MVC
- Spring Data
- https://flywaydb.org[Flyway] – for database migration
- https://projectlombok.org[Project Lombok] – for low level code generation
- https://www.vavr.io/[Vavr] – for a better more functional programming style

[[lombok]]
IMPORTANT: Make sure you have the Lombok plugin installed in your IDE so that your code can compile correctly.

== Development

For general information about development (commit messages, branching, …), see the iris-client repository.

https://github.com/iris-connect/iris-client#dev

=== Java parts

Since most Java code of IRIS will be developed in the IRIS client BFF, please refer to its documentation for instructions on developing Java code.

https://github.com/iris-connect/iris-client#java
