CREATE TABLE LOCATION (
    LOCATION_ID VARCHAR(255) NOT NULL,
    PROVIDER_ID VARCHAR(255) NOT NULL,
    CONTACT_ADDRESS_CITY VARCHAR(255),
    CONTACT_ADDRESS_STREET VARCHAR(255),
    CONTACT_ADDRESS_ZIP VARCHAR(255),
    CONTACT_EMAIL VARCHAR(255),
    CONTACT_OFFICIAL_NAME VARCHAR(255),
    CONTACT_OWNER_EMAIL VARCHAR(255),
    CONTACT_PHONE VARCHAR(255),
    CONTACT_REPRESENTATIVE VARCHAR(255),
    NAME VARCHAR(255),
    CONSTRAINT location_pkey PRIMARY KEY (LOCATION_ID, PROVIDER_ID)
)
